name: MyRoleplaySystem
version: '${project.version}'
main: com.basis.main.main
api-version: 1.18
authors: [ Nihar ]

softdepend: [Vault, PlaceholderAPI, ProtocolLib]

commands:
  Test:
    usuage: /Test
  Interaction:
    usuage: /Interaction
  Dataprotection:
    usuage: /Dataprotection
    aliases: [Datenschutzerklärung,Datenschutz]
  Textblock:
    usuage: /Textblock
    aliases: [text]
  Hologram:
    usuage: /Hologram
    aliases: [holo, hd]
  MRS:
    usuage: /MRS
    aliases: [MyRoleplaySystem]
  NPC:
    usuage: /NPC
  IBlock:
    usuage: /IBlock
    aliases: [ifield]
  Position:
    usuage: /Position
    aliases: [pos]