name: MyRoleplaySystem
version: '${project.version}'
main: com.basis.main.main
api-version: 1.18
authors: [ Nihar ]

softdepend: [Vault, PlaceholderAPI, ProtocolLib]

commands:
  Test:
    usuage: /Test
    tab-complete: true
  Interaction:
    usuage: /Interaction
    tab-complete: false
  Dataprotection:
    usuage: /Dataprotection
    tab-complete: true
  Textblock:
    usuage: /Textblock
    aliases: [text]