name: MyRoleplaySystem
version: '${project.version}'
main: com.basis.main.main
api-version: 1.18
authors: [ Nihar ]

softdepend: [Vault, PlaceholderAPI, ProtocolLib]

commands:
  Test:
    usuage: /Test
  Interaction:
    usuage: /Interaction
  Dataprotection:
    usuage: /Dataprotection
  Textblock:
    usuage: /Textblock
    aliases: [text]
  Hologram:
    usuage: /Hologram
    aliases: [holo, hd]
  NPC:
    usuage: /NPC
  IField:
    usuage: /IField