name: MyRoleplaySystem
version: '${project.version}'
main: com.basis.main.main
api-version: 1.18
authors: [ Nihar ]

softdepend: [Vault, PlaceholderAPI, ProtocolLib, WorldGuard]

commands:
  Test:
    usuage: /Test
  Interaction:
    usuage: /Interaction
  Dataprotection:
    usuage: /Dataprotection
  Textblock:
    usuage: /Textblock
  Hologram:
    usuage: /Hologram
  MRS:
    usuage: /MRS
  NPC:
    usuage: /NPC
  IBlock:
    usuage: /IBlock
  Position:
    usuage: /Position
  Select:
    usuage: /Select
  Plot:
    usuage: /Plot
  Label:
    usuage: /Label